name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SH_PRIVATE_KEY }}
          script: |
            set -e
            echo "Starting deployment..."
            cd /opt/odoo/custom_addons/AgenticBrain

            git config --global --add safe.directory /opt/odoo/custom_addons/AgenticBrain

            REPO_URL="https://AhmedEmary:${{ secrets.PAT }}@github.com/AhmedEmary/AgenticBrain.git"
            git fetch "$REPO_URL" main
            git reset --hard FETCH_HEAD

            sudo chown -R odoo:odoo /opt/odoo/custom_addons/AgenticBrain
            sudo systemctl restart odoo

            echo "Deployment successful!"
